FROM debian:buster

EXPOSE 3306

ARG MYSQL_DATABASE
ARG MYSQL_USER
ARG MYSQL_PASSWORD
ARG MYSQL_ROOT_PASSWORD 

ENV MYSQL_DATABASE=${MYSQL_DATABASE}
ENV MYSQL_USER=${MYSQL_USER}
ENV MYSQL_PASSWORD=${MYSQL_PASSWORD}
ENV MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

RUN apt-get update && apt-get install mariadb-server -y && \
	rm -rf /var/lib/apt/lists/*

# RUN rm /etc/mysql/mariadb.conf.d/50-server.cnf
COPY conf/50-server.cnf /etc/mysql/mariadb.conf.d

# initializes the MySQL data directory and creates the system tables that it contains, if they do not exist.
RUN mysql_install_db

COPY tools/setup.sh /var/
# RUN service mysql start && bash /var/www/setup.sh
RUN chmod +x /var/setup.sh
# RUN sleep 1000000
RUN /var/setup.sh


ENTRYPOINT ["mysqld_safe"]
