# wordpress
FROM debian:buster

RUN apt -y update && apt -y upgrade && apt install -y \
    wget			\
    php7.3			\
    php-fpm         \
    php-mysql

EXPOSE 9000

RUN echo '[www]' > /etc/php/7.3/fpm/pool.d/www.conf
RUN echo 'user = www-data' >> /etc/php/7.3/fpm/pool.d/www.conf
RUN echo 'group = www-data' >> /etc/php/7.3/fpm/pool.d/www.conf
RUN echo 'listen = wordpress:9000' >> /etc/php/7.3/fpm/pool.d/www.conf
RUN echo 'pm = dynamic' >> /etc/php/7.3/fpm/pool.d/www.conf
RUN echo 'pm.start_servers = 6' >> /etc/php/7.3/fpm/pool.d/www.conf
RUN echo 'pm.max_children = 25' >> /etc/php/7.3/fpm/pool.d/www.conf 
RUN echo 'pm.min_spare_servers = 2' >> /etc/php/7.3/fpm/pool.d/www.conf
RUN echo 'pm.max_spare_servers = 10' >> /etc/php/7.3/fpm/pool.d/www.conf

COPY ./conf/setup.sh /setup.sh
RUN chmod +x /setup.sh
ENTRYPOINT ["bash", "/setup.sh"]

CMD ["/usr/sbin/php-fpm7.3", "--nodaemonize"]
